# Generated by Django 3.1.2 on 2021-01-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingatlan_allapota', models.CharField(blank=True, choices=[(0, 'uj'), (1, 'normal'), (2, 'felujitando')], max_length=50, null=True)),
                ('epites_eve', models.CharField(blank=True, max_length=50, null=True)),
                ('komfort', models.CharField(blank=True, max_length=50, null=True)),
                ('energiatanusitvany', models.CharField(blank=True, max_length=50, null=True)),
                ('emelet', models.CharField(blank=True, max_length=50, null=True)),
                ('epulet_szintjei', models.PositiveIntegerField(blank=True, null=True)),
                ('lift', models.BooleanField(blank=True, null=True)),
                ('belmagassag', models.PositiveIntegerField(blank=True, null=True)),
                ('futes', models.CharField(blank=True, choices=[(0, 'gaz'), (1, 'villany'), (2, 'kalyha')], max_length=50, null=True)),
                ('legkondicionalo', models.BooleanField(blank=True, null=True)),
                ('akadalymentesitett', models.BooleanField(blank=True, null=True)),
                ('furdo_WC', models.BooleanField(blank=True, null=True)),
                ('tajolas', models.CharField(blank=True, choices=[(0, 'E'), (1, 'D'), (2, 'K'), (3, 'NY')], max_length=50, null=True)),
                ('kilatas', models.CharField(blank=True, max_length=50, null=True)),
                ('kertkapcsolatos', models.BooleanField(blank=True, null=True)),
                ('tetoter', models.BooleanField(blank=True, null=True)),
                ('pince', models.BooleanField(blank=True, null=True)),
                ('parkolas', models.BooleanField(blank=True, null=True)),
                ('beepithetoseg', models.CharField(blank=True, max_length=50, null=True)),
                ('szintteruleti_mutato', models.PositiveIntegerField(blank=True, null=True)),
                ('brutto_szintterulet', models.PositiveIntegerField(blank=True, null=True)),
                ('villany', models.BooleanField(blank=True, null=True)),
                ('viz', models.BooleanField(blank=True, null=True)),
                ('gaz', models.BooleanField(blank=True, null=True)),
                ('csatorna', models.BooleanField(blank=True, null=True)),
                ('telek_besorolas', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='House.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.data'),
        ),
    ]
