# Generated by Django 3.1.2 on 2021-02-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0007_auto_20210207_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Eladó', 'Eladó'), ('Kiadó', 'Kiadó')], max_length=20),
        ),
        migrations.AlterField(
            model_name='types',
            name='status',
            field=models.CharField(choices=[('Ház', 'Ház'), ('Lakás', 'Lakás'), ('Telek', 'Telek')], max_length=20),
        ),
    ]
