# Generated by Django 3.1.2 on 2021-02-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0008_auto_20210207_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('slug', models.CharField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'CityParts',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='city',
            name='city_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='House.citypart'),
        ),
    ]
