# Generated by Django 3.1.2 on 2021-02-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0011_auto_20210207_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_part',
        ),
        migrations.DeleteModel(
            name='CityPart',
        ),
    ]
